import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { auth } from "../../auth";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/shared/Footer/Footer";

const bebasNeue = localFont({
  src: "../../public/fonts/BebasNeueProBold.woff2",
  variable: "--bebasNeue",
  display: "swap",
});

const SFUIRegular = localFont({
  src: "../../public/fonts/SFUIRegular.ttf",
  variable: "--SFUIRegular",
  display: "swap",
});

const SFUIMedium = localFont({
  src: "../../public/fonts/SFUIMedium.woff",
  variable: "--SFUIMedium",
  display: "swap",
});

const BaskervilleBT = localFont({
  src: "../../public/fonts/BaskervilleBT.woff2",
  variable: "--BaskervilleBT",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body
          className={`${bebasNeue.variable} ${SFUIRegular.variable} ${BaskervilleBT.variable} ${SFUIMedium.variable}`}
        >
          {children}
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
