import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bebasNeue = localFont({
  src: "../../public/fonts/BebasNeueProBold.woff2",
  variable: "--bebasNeue",
  display: "swap",
});

const SFUIRegular = localFont({
  src: "../../public/fonts/SFUIRegular.ttf",
  variable: "--SFUIRegular",
  display: "swap",
});

const SFUIMedium = localFont({
  src: "../../public/fonts/SFUIMedium.woff",
  variable: "--SFUIMedium",
  display: "swap",
});

const BaskervilleBT = localFont({
  src: "../../public/fonts/BaskervilleBT.woff2",
  variable: "--BaskervilleBT",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${bebasNeue.variable} ${SFUIRegular.variable} ${BaskervilleBT.variable} ${SFUIMedium.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
